#!/bin/bash
echo "=========================================="
echo "  Ground for Android - Project Info"
echo "=========================================="
echo ""
echo "This is a native Android application."
echo "It requires the Android SDK to build and run."
echo ""
echo "Project Structure:"
echo "------------------"
echo "  app/              - Main Android application module"
echo "  core/domain/      - Kotlin Multiplatform business logic"
echo "  core/ui/          - Kotlin Multiplatform shared UI (Compose)"
echo "  e2eTest/          - End-to-end tests"
echo "  sharedTest/       - Shared test utilities"
echo ""
echo "Build Tool: Gradle $(./gradlew --version 2>&1 | grep '^Gradle' | awk '{print $2}')"
echo "Java: $(java -version 2>&1 | head -1)"
echo ""
echo "Key Technologies:"
echo "-----------------"
echo "  - Kotlin + Jetpack Compose"
echo "  - Firebase (Firestore, Auth, Storage)"
echo "  - Google Maps SDK"
echo "  - Hilt (Dependency Injection)"
echo "  - Room (Local DB)"
echo "  - Kotlin Coroutines + Flow"
echo ""
echo "Kotlin files:"
find . -name "*.kt" -not -path "*/build/*" -not -path "*/.gradle/*" 2>/dev/null | wc -l | xargs echo "  Total .kt files:"
echo ""
echo "To build this app, you need:"
echo "  1. Android SDK (ANDROID_HOME set)"
echo "  2. Android SDK Platform 36"
echo "  3. Android Build Tools"
echo ""
echo "See CONTRIBUTING.md for setup instructions."
echo "=========================================="
